# -*- coding: utf-8 -*-
"""GS_Anna_Karen_Thalita (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7KkEWt6PcqYWu84zDVkjejwFxg1mwn4

# **Global Solution: Integrantes**
Anna Luiza Torra 563388
Karen Akemi 562733
Thalita Soares 566381

1. Realize uma descrição dos dados conforme o que se pede(mapa_desastres.csv)
a) Quantas linhas e colunas?
b) Quantos municípios e UF's temos na base?
c) Qual o período mínimo e máximo registrado?
d) Quantas e quais "descrições de tipologia" temos base?
"""

import pandas as pd

df = pd.read_csv('mapa_desastres_br.csv', encoding='ISO-8859-1', sep=';')
df.head(1)

# Exercício A
colunas = len(df.columns)
linhas = len(df.index)
print("Respostas exercício 1 \n")
print(f"O número de colunas é de: {colunas}")
print(f"O número de linhas é de: {linhas} \n")

# Exercício B
municipios = df['Cod_IBGE_Mun'].nunique()
ufs = df['Sigla_UF'].nunique()
print(f"Quantidade de municípios: {municipios}")
print(f"Quantidade de UF's: {ufs} \n")

# Exercício C
período_min = df['Data_Evento'].min()
período_max = df['Data_Evento'].max()
print(f"Período mínimo: {período_min}")
print(f"Período máximo: {período_max} \n")

# Exercício D
descricoes = df['tipologia'].unique()
descricoes2 = df['descricao_tipologia'].unique()
print(f"Quantidade de descrições: {len(descricoes)}")
print(f"Descrições: {descricoes2}")

"""2. Segundo o Blog "Homem neutro", o governo atual não tem dado tanta atenção aos inc~endios florestais. De acordo co os jornalistas, o número de incêndios aumentou drasticamente desde o início do governo atual.
a) Analise a frequência de incêndios florestais antes e depois do governo.
b) Gere um gráfico mostrando as diferenças.
c) Classifique como "Fake" ou "Not Fake".
d) Seria possível defender seu contratante neste caso? Como você o defenderia (usando dados)?
"""

import pandas as pd
from datetime import datetime

df = pd.read_csv('mapa_desastres_br.csv', encoding='ISO-8859-1', sep=';')
df.head(1)

df['Data_Evento'] = pd.to_datetime(df['Data_Evento'], errors='coerce')
incendios = df[df['descricao_tipologia'].str.contains('Incêndio Florestal', case=False, na=False)]
entre_2016_2020 = incendios[(incendios['Data_Evento'].dt.year >= 2016) & (incendios['Data_Evento'].dt.year <= 2020)].shape[0]
de_2021_mais = incendios[incendios['Data_Evento'].dt.year >= 2021].shape[0]

print("Frequência total de incêndios florestais:")
print(f"De 2016 a 2020 (Antes): {entre_2016_2020}")
print(f"A partir de 2021 (Depois): {de_2021_mais}")

plt.bar(['2016-2020','A partir de 2021'] , [entre_2016_2020, de_2021_mais], color=["green" , "red"])
plt.title('Frequência de Incêndios Florestais\nPeríodo 2016-2020 vs. 2021+')
plt.ylabel('Quantidade de Incêndios')
plt.xlabel('Período')
plt.show()

if de_2021_mais > entre_2016_2020:
    resultado = "Not Fake"
else:
    resultado = "Fake"

print(f"{resultado}")

# Defesa
print("Tendo em vista os dados descritivos dos relatórios de incêndio,\n há a consolidação do argumento de que o presidente que governou entre os anos de 2016 até 2020 \n foi responsável por diminuir o total de incêndios florestais. Algo que a preocupação do próprio, \n surtiu efeito posisitvo para estes resultados o qual evidentemente, de acordo com as análises e o gráfico, \n mostra certa postura negligente do atual governo. ")

"""3. A conta do X "@SomosDoBrasilOficial" postou a seguinte frase: "Nunca houve na história desse país tantos desabrigados!!! #semcasasempaz". Faça o que se pede:
a) Gerar um dataset contendo o histórico em SP do número de desabrigados.
b) Gere um gráfico histórico tentando identificar o pico de desabrigados.
c) classifique como "Fake" ou "Not Fake"
d) Qual postagem o governo deveria fazer para responder a esta afirmação?
"""

import pandas as pd
import matplotlib.pyplot as plt

dados = pd.read_csv('mapa_desastres_br.csv', encoding='ISO-8859-1', sep=';')

dados_sp = dados[dados['Sigla_UF'] == 'SP']
desabrigados_sp = dados_sp.groupby(pd.to_datetime(dados_sp['Data_Evento']))['DH_DESABRIGADOS'].sum().reset_index()
desabrigados_sp['Ano'] = pd.to_datetime(desabrigados_sp['Data_Evento']).dt.year
desabrigados_por_ano = desabrigados_sp.groupby('Ano')['DH_DESABRIGADOS'].sum().reset_index()

plt.figure(figsize=(8,5))
plt.plot(desabrigados_por_ano['Ano'], desabrigados_por_ano['DH_DESABRIGADOS'], marker='o', color='darkred')
plt.title('Desabrigados em São Paulo')
plt.xlabel('Ano')
plt.ylabel('Quantidade')
plt.grid(visible=True)
plt.show()

maior_valor = desabrigados_por_ano['DH_DESABRIGADOS'].max()
ano_maior = desabrigados_por_ano.loc[desabrigados_por_ano['DH_DESABRIGADOS'].idxmax(), 'Ano']

print("\nVerificação")
if ano_maior == 2024:
    status = "Not Fake"
else:
    status = "Fake"

print(f"O maior número de desabrigados foi {maior_valor} no ano de {ano_maior}.")
print(f"Classificação: {status}")

print("\nMensagem do governo")
if status == "Not Fake":
    mensagem = ("Diante dos dados mais recentes, confirmamos que o número de desabrigados em São Paulo atingiu o maior patamar já registrado na série histórica. Estamos mobilizando todos os recursos necessários para oferecer acolhimento, assistência e suporte às famílias afetadas, além de reforçar nossas ações de prevenção e enfrentamento.")
else:
    mensagem = (
        "O governo esclarece que o número atual de desabrigados em São Paulo "
        "não é o maior da série histórica. Estamos trabalhando continuamente "
        "para reduzir os impactos e prestar assistência. Dessa forma, avançamos para a construção"
        "De um país cada vez mais sólido e estruturado."
    )

print(mensagem)

"""4. A equipe de analistas do partido de oposição (Partido dos Liberais Conservadores - PLC) lançou um vídeo em todas as redes oficiais sobre as instituições de ensino estarem abandonadas. De acordo com seus analistas, "durante o período o governo as instituiuções danificadas cresceram 5%, destruídas cresceram 7% e no total 10%".
a) Gerar um dataset contendo o histórico em SP do número de instituições de ensino danificadas, destruídas e a soma das duas.
b) Compare estes percentuais nos períodos antes e depois do governo.
c) Classifique como "Fake" ou "Not Fake"
d) Qual postagem o governo deveria fazer para responder esta afirmação?
"""

# Exercício A
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('mapa_desastres_br.csv', encoding='ISO-8859-1', sep=';')

df_sp_educ = df[
    (df['Sigla_UF'] == 'SP') &
    ((df['DM_Inst_Ensino_Danificadas'] > 0) |
     (df['DM_Inst_Ensino_Destruidas'] > 0))
].copy()

df_sp_educ['Data_Evento'] = pd.to_datetime(df_sp_educ['Data_Evento'])
df_sp_educ['Ano'] = df_sp_educ['Data_Evento'].dt.year

df_sp_educ = df_sp_educ[df_sp_educ['Ano'].between(2016, 2023)]

df_historico_sp = df_sp_educ.groupby('Ano').agg(
    Instituicoes_Danificadas=('DM_Inst_Ensino_Danificadas', 'sum'),
    Instituicoes_Destruidas=('DM_Inst_Ensino_Destruidas', 'sum')
).reset_index()

df_historico_sp['Total_Afetadas'] = (
    df_historico_sp['Instituicoes_Danificadas'] +
    df_historico_sp['Instituicoes_Destruidas']
)

df_historico_sp = df_historico_sp.sort_values('Ano')

print(df_historico_sp.to_string(index=False))

#   Exercício B

def calcular_estatisticas(df, anos):
    periodo = df[df['Ano'].between(anos[0], anos[1])]
    return {
        'Danificadas': periodo['Instituicoes_Danificadas'].mean(),
        'Destruidas': periodo['Instituicoes_Destruidas'].mean(),
        'Total': periodo['Total_Afetadas'].mean()
    }

media_oposicao = calcular_estatisticas(df_historico_sp, [2016, 2020])
media_governo = calcular_estatisticas(df_historico_sp, [2021, 2023])

variacao = {
    'Danificadas': ((media_governo['Danificadas'] - media_oposicao['Danificadas']) / media_oposicao['Danificadas']) * 100,
    'Destruidas': ((media_governo['Destruidas'] - media_oposicao['Destruidas']) / media_oposicao['Destruidas']) * 100,
    'Total': ((media_governo['Total'] - media_oposicao['Total']) / media_oposicao['Total']) * 100
}

print(f"""\n
Governo da Oposição (2016-2020)
Média anual:
- Danificadas: {media_oposicao['Danificadas']:.1f}
- Destruídas: {media_oposicao['Destruidas']:.1f}
- Total: {media_oposicao['Total']:.1f}

Governo atual (2021-2023)
Média anual:
- Danificadas: {media_governo['Danificadas']:.1f}
- Destruídas: {media_governo['Destruidas']:.1f}
- Total: {media_governo['Total']:.1f}

VARIAÇÃO PERCENTUAL
- Danificadas: {variacao['Danificadas']:.1f}%
- Destruídas: {variacao['Destruidas']:.1f}%
- Total: {variacao['Total']:.1f}%
""")

# Exercício C
if variacao['Total'] < 0:
    status = "Fake"
    print(f"Classificação: {status}")
    print("A narrativa do PLC não reflete a realidade. Estamos trabalhando intensamente para melhorar todas as escolas, com resultados concretos que beneficiam alunos e professores em todo o país"
    "Além do mais, vocês devem reconhecer que grandes soluções devem ser tomadas de forma responsável. Diante disso o governo faz jus para essa situação a fim de reduzir os impactos na educação."
    )
else:
    status = "Not Fake"
    print(f"Classificação: {status}")
    print("Reconhecemos os desafios nas escolas e já agimos com reformas emergenciais. Os dados do PLC reforçam a necessidade de investirmos mais na educação, nossa prioridade.")

"""5) [3 pontos] Está acontecendo uma manifestação na avenida Paulista de mais 400 mil de pessoas. Segundo os manifestantes, o governo perdeu
o controle em relação aos desastres dos últimos anos. A quantidade de mortes, feridos, enfermos e desabrigados estão fora dos limites. Estão
cogitando pedir a saída do atual governo.
Analise os dados e realize todas as análises necessárias para defender de todos os ataques dos manifestantes. Lembre-se que os jornalistas
estão sedentos por respostas. Demonstre diversas análises sobre mortes, feridos, enfermos e desabrigados. Além disso, levante os gastos com danos materiais que o governo tem enfrentado.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('mapa_desastres_br.csv', encoding='ISO-8859-1', sep=';')
df.head(1)

df.columns.tolist()

df[df['regiao'] == 'Sudeste'].shape
df_sp = df[df['regiao'] == 'Sudeste'].copy()

try:
    df_sp['Data_Evento'] = pd.to_datetime(df_sp['Data_Evento'], errors='coerce')
    df_sp = df_sp.dropna(subset=['Data_Evento'])
    df_sp = df_sp[df_sp['Data_Evento'].dt.year >= 2016]
    df_sp.shape
except Exception as e:
    print(f"\nErro ao converter datas: {e}")

if df_sp.empty:
    print("\nAVISO: O DataFrame está vazio após os filtros. Verifique:")
else:
    df_sp['Governo'] = df_sp['Data_Evento'].apply(
        lambda x: 'Oposição (2016-2020)' if x.year <= 2020 else 'Atual (2021-2023)'
    )

    metric_cols = ['DH_MORTOS', 'DH_FERIDOS', 'DH_ENFERMOS', 'DH_DESABRIGADOS', 'DM_total_danos_materiais']
    available_cols = [col for col in metric_cols if col in df_sp.columns]

    if 'DM_total_danos_materiais' in available_cols:
        df_sp['DM_total_danos_materiais'] = (
            df_sp['DM_total_danos_materiais']
            .astype(str)
            .replace(r'[^\d,.-]', '', regex=True)
            .str.replace('.', '', regex=False)
            .str.replace(',', '.', regex=False)
            .astype(float)
        )

    if not available_cols:
        print("\nAVISO: Nenhuma coluna de métricas encontrada.")
        print(df_sp.columns.tolist())
    else:
        metrics = df_sp.groupby('Governo')[available_cols].sum().reset_index()
        print("\nComparação entre governos:")
        print(metrics.to_string(index=False))

        df_sp['Ano'] = df_sp['Data_Evento'].dt.year
        annual_metrics = df_sp.groupby('Ano')[available_cols].sum().reset_index()
        print("\nEvolução Anual:")
        print(annual_metrics.to_string(index=False))

        if 'grupo_de_desastre' in df_sp.columns:
            disaster_types = df_sp.groupby(['Governo', 'grupo_de_desastre']).size().unstack(fill_value=0)
            print("\nTipos de Desastre por Governo:")
            print(disaster_types.to_string())
    print("Com as análises é possível observar que o número de mortes, feridos, enfermos e desabrigados é muito menor que o do governo anterior (governo atual: 57.696 ao todo e o governo anterior: 90.210 ao todo). As despesas em danos materiais foram maiores mas deve ser levado em consideração que muitos dos gastos podem ser consequências do governo anterior.")